package alekseybykov.portfolio.springboot.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import https.spring_boot_soap_alekseybykov_github.DataServicePortType;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-06-20T14:21:06.311+03:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "SoapWSService",
                  wsdlLocation = "file:/C:/java-projects/spring-boot-ws/soap-client/src/main/resources/wsdl/DataService.wsdl",
                  targetNamespace = "http://ws.springboot.portfolio.alekseybykov/")
public class SoapWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.springboot.portfolio.alekseybykov/", "SoapWSService");
    public final static QName SoapWSPort = new QName("http://ws.springboot.portfolio.alekseybykov/", "SoapWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/java-projects/spring-boot-ws/soap-client/src/main/resources/wsdl/DataService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SoapWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/java-projects/spring-boot-ws/soap-client/src/main/resources/wsdl/DataService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SoapWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SoapWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SoapWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SoapWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DataServicePortType
     */
    @WebEndpoint(name = "SoapWSPort")
    public DataServicePortType getSoapWSPort() {
        return super.getPort(SoapWSPort, DataServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataServicePortType
     */
    @WebEndpoint(name = "SoapWSPort")
    public DataServicePortType getSoapWSPort(WebServiceFeature... features) {
        return super.getPort(SoapWSPort, DataServicePortType.class, features);
    }

}
