package https.spring_boot_soap_alekseybykov_github;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-06-20T14:07:47.424+03:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "https://spring-boot-soap.alekseybykov.github.io/", name = "DataServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DataServicePortType {

    @WebMethod
    @WebResult(name = "getDataResponse", targetNamespace = "https://spring-boot-soap.alekseybykov.github.io/", partName = "parameters")
    public GetDataResponse getData(
        @WebParam(partName = "parameters", name = "getDataRequest", targetNamespace = "https://spring-boot-soap.alekseybykov.github.io/")
        GetDataRequest parameters
    );

    @WebMethod
    @WebResult(name = "createDataResponse", targetNamespace = "https://spring-boot-soap.alekseybykov.github.io/", partName = "parameters")
    public CreateDataResponse createData(
        @WebParam(partName = "parameters", name = "createDataRequest", targetNamespace = "https://spring-boot-soap.alekseybykov.github.io/")
        CreateDataRequest parameters
    );
}
