package https.spring_boot_soap_alekseybykov_github;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-06-20T14:07:47.471+03:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "DataService",
                  wsdlLocation = "file:/C:/java-projects/spring-boot-ws/soap-ws/src/main/resources/wsdl/DataService.wsdl",
                  targetNamespace = "https://spring-boot-soap.alekseybykov.github.io/")
public class DataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://spring-boot-soap.alekseybykov.github.io/", "DataService");
    public final static QName DataServicePort = new QName("https://spring-boot-soap.alekseybykov.github.io/", "DataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/java-projects/spring-boot-ws/soap-ws/src/main/resources/wsdl/DataService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/java-projects/spring-boot-ws/soap-ws/src/main/resources/wsdl/DataService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DataServicePortType
     */
    @WebEndpoint(name = "DataServicePort")
    public DataServicePortType getDataServicePort() {
        return super.getPort(DataServicePort, DataServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataServicePortType
     */
    @WebEndpoint(name = "DataServicePort")
    public DataServicePortType getDataServicePort(WebServiceFeature... features) {
        return super.getPort(DataServicePort, DataServicePortType.class, features);
    }

}
